version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - '8081:8081'
    volumes:
      - ./backend:/app
    env_file:
      - ./env/back.env
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    env_file:
      - ./env/front.env

